---
swagger: '2.0'
info:
  version: 1.0.0
  title: Version Service
  description: RESTful service to create and query application version
schemes:
  - http
basePath: /version-service/v1
consumes:
  - application/json
paths:
  /environment:
    get:
        description: Retrieves a list of known environment
        responses:
          200:
            description: A list of known environments
            schema:
              type: array
              items:
                type: string
          500:
            description: Server error
  /environment/{id}:
    get:
      description: Retrieves a list of applications and the versions for the environment for the given date
      parameters:
        - name: id
          in: path
          type: string
          required: true
        - name: date
          in: query
          type: string
          format: date-type
          required: false
        - name: product
          in: query
          type: string
          required: false
      responses:
        200:
          description: A list of applications and the version deployed into the given environment
          schema:
            type: array
            items:
              $ref: '#/definitions/Environment'
        500:
          description: Server error
  /version:
    get:
      description: Retrieves a list of application versions
      parameters:
        - name: environment
          in: query
          type: string
          required: false
        - name: application_name
          in: query
          type: string
          required: false
        - name: product
          in: query
          type: string
          required: false
      responses:
        200:
          description: A list of application versions
          schema:
            type: array
            items:
              $ref: '#/definitions/ApplicationVersion'
        500:
          description: Server error
    post:
      description: Create an application version entity and returns the id
      parameters:
        - name: application_version
          in: body
          required: true
          schema:
            $ref: "#/definitions/ApplicationVersionCreate"
      responses:
        201:
          description: Application Version id
          schema:
            $ref: '#/definitions/ApplicationVersionSuccessful'
        400:
          description: Validation error
        500:
          description: Server error
definitions:
    ApplicationVersion:
      type: object
      properties:
        _id:
          type: string
        updated_at:
          type: string
          format: date-time
        date:
          type: string
          format: date-time
        environment:
          type: string
        application_name:
          type: string
        version:
          type: string
        product:
          type: string
        __v:
          type: string
    ApplicationVersionCreate:
      type: object
      properties:
        environment:
          type: string
        application_name:
          type: string
        version:
          type: string
        product:
          type: string
    ApplicationVersionSuccessful:
      type: object
      properties:
        id:
          type: string
    Environment:
      type: object
      properties:
        application_name:
          type: string
        version:
          type: string
