---
swagger: '2.0'
info:
  version: 0.0.1
  title: Version Service
  description: RESTful service to query aplication versions
schemes:
  - http
basePath: /version-service/v1
consumes:
  - application/json
paths:
  /version:
    get:
      description: Get all versions
      parameters:
        - name: fact_find_id
          description: One or many (comma delimited) fact_find_ids to match
          in: query
          type: string
          required: false
        - name: _id
          description: One or many (comma delimited) solution _ids to match
          in: query
          type: string
          required: false
        - name: fields
          description: One or many (comma delimited) solution fields to return
          in: query
          type: string
          required: false
definitions:
    VersionSuccessful:
      type: object
      properties:
        _id:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        fact_find_id:
          type: string
        solution:
          type: object
