---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: version-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: version-service
        tier: backend
    spec:
      containers:
      - name: version-service
        image: 293630037826.dkr.ecr.eu-west-1.amazonaws.com/version-service:1.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 0.15
        env:
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: version.service.secrets
                key: mongodb.url
---
kind: Service
apiVersion: v1
metadata:
  name: version-service
spec:
  selector:
    app: version-service
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: version-service
spec:
  rules:
  - host: apps.st.wealthwizards.io
    http:
      paths:
      - path: /version-service
        backend:
          serviceName: version-service
          servicePort: 80
