version: 2
jobs:
  build:
    docker:
      - image: quay.io/wealthwizards/ww-base-node:alpine-14
        environment:
          MONGODB_URL: mongodb://127.0.0.1:27017/version_service
      - image: mongo:3.4.1
    working_directory: /usr/src
    steps:
      - add_ssh_keys
      - run:
          name: install-git-ssh
          command: apk update && apk add git openssh
      - checkout
      - run:
          name: install-tap-xunit
          command: npm install tap-xunit
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: unit-tests
          command: npm run test:unit
      - run:
          name: component-tests
          command: npm run test:component
  buildAndDeploy:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : patch-application
          command: |
            git config --global user.email "circleci@wealthwizards.com"
            git config --global user.name "Circle CI"
            npm version patch -m "Release %s [ci skip]" > .version
            sed -i 's/^v//g' .version
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/version-service .
            docker tag quay.io/wealthwizards/version-service quay.io/wealthwizards/version-service:$(cat .version)
      - deploy:
          name : deploy-git-changes
          command: git push --follow-tags
      - deploy:
          name : deploy-docker-image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS quay.io
            docker push quay.io/wealthwizards/version-service
            docker push quay.io/wealthwizards/version-service:$(cat .version)
  buildDockerImage:
    machine: true
    steps:
      - add_ssh_keys
      - checkout
      - run:
          name : build-docker-image
          command: |
            docker build -t quay.io/wealthwizards/version-service .
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - buildDockerImage:
          filters:
            branches:
              ignore: master
      - buildAndDeploy:
          requires:
            - build
          filters:
            branches:
              only: master
